[package]
name = "passgen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.4" ,features = [ "derive" ]}
serde = {version = "1.0.203", features = [ "derive" ]}
rand = "0.8.5"
rand_distr = "0.4.2"